<?php
include('../Config.php');

session_start();


if (isset($_POST['submit-recette'])) {
    $name = $_POST['Nom_recette'];
    $time = $_POST['temps_preparation'];
    $number_pp = $_POST['nbre_personne'];
    $difficulty = $_POST['difficulte'];
    $type = $_POST['type_plat'];
    $ing = $_POST['ing'];

    // $dom = new DOMDocument();

    // // Get the HTML content generated by the PHP file
    // $html = file_get_contents('../index.php');

    // // Load the HTML content into the DOMDocument object
    // $dom->loadHTML($html);

    // // Get the ol element by its ID
    // $ol = $dom->getElementById('list');

    // // Get all the li elements inside the ol
    // $li_list = $ol->getElementsByTagName('li');

    // // Loop through the li elements and get their text content
    // foreach ($li_list as $li) {
    //     $text = $li->textContent;
    //     echo $text . '<br>';
    //}
    // if (isset($_POST['list'])) {

    //     foreach ($_POST['list'] as $item) {
    //         // $liText = strip_tags($item); // Remove any HTML tags
    //         $instruction .= $item . "<br>";
    //     }
    // } else {
    //     header("Location: ../index.php?error=No instructions");
    //     die;
    // }

    if (isset($_FILES['video']['name']) && !empty($_FILES['video']['name'])) {
        $video = $_FILES['video']['name'];
        $video_tmp_name = $_FILES['video']['tmp_name'];
        $video_size = $_FILES['video']['size'];
        $video_folder = '../assets/videos/recette/' . $video;

        // Check if the uploaded file is a video
        $allowed_types = array('mp4', 'avi', 'mov');
        $file_ext = strtolower(pathinfo($video, PATHINFO_EXTENSION));
        if (!in_array($file_ext, $allowed_types)) {
            header("Location: ../index.php?error=Invalid file type");
            die;
        }

        // Check if the uploaded file is a video and the upload was successful
        if ($_FILES['video']['error'] !== UPLOAD_ERR_OK) {
            header("Location: ../index.php?error=File upload failed");
            die;
        }

        $query = mysqli_prepare($con, "insert into recette (name,prep_time,nb_people,difficulty,type,video,user_id) values (?,?,?,?,?,?,?)");
        mysqli_stmt_bind_param($query, "sssssss", $name, $time, $number_pp, $difficulty, $type, $video, $_SESSION['id']);

        if (mysqli_stmt_execute($query)) {
            move_uploaded_file($video_tmp_name, $video_folder);
        }

    } else {
        $query = mysqli_prepare($con, "insert into recette (name,prep_time,nb_people,difficulty,type,user_id) values (?,?,?,?,?,?)");
        mysqli_stmt_bind_param($query, "ssssss", $name, $time, $number_pp, $difficulty, $type, $_SESSION['id']);
        mysqli_stmt_execute($query);
    }

    $sql = "SELECT * FROM recette Where name = '$name';";
    $select_recette = mysqli_query($con, $sql);
    $fetch_recette = mysqli_fetch_assoc($select_recette);

    // if (isset($_FILES['image']['tmp_name']) && !empty($_FILES['image']['tmp_name'])) {
    //     foreach ($_FILES['image']['tmp_name'] as $index => $tmpName) {
    //         // Get the image data from the temporary file
    //         $name_img = $_FILES['image']['name'][$index];
    //         $type = $_FILES['image']['type'][$index];
    //         $data = file_get_contents($tmpName);
    //         $img_folder = "../assets/img/recette/" . $name_img;


    //         $query2 = mysqli_prepare($con, "insert into recette_images (name,image,recette_id) values (?,?,?)");
    //         mysqli_stmt_bind_param($query2, "sss", $name_img, $data, $fetch_recette['id']);

    //         if (mysqli_stmt_execute($query2)) {
    //             move_uploaded_file($tmpName, $img_folder);

    //             header("Location: ../index.php?success=Recipe added succesfully");
    //         }
    //     }
    // } else {
    //     // header("Location: ../index.php?success=Recipe added succesfully");
    // }
}
?>